version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapi_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  strapi:
    container_name: strapi-app
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  go-api:
    container_name: go-api
    build: ./go-api
    restart: unless-stopped
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
      API_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pg_data:
